url: http://blogaus-testailu.github.io
title: Blogaüs-testailu
description: Blogaüs-testailu
paginate: 5
paginate_path: "/:num"
pygments: true
markdown: rdiscount

authors:
  trinne:
    name: Tuomas Rinne
    email: torinne@gmail.com
    url: mailto:torinne@gmail.com
